### ISSUE TITLE
[Feature Request] Help Page (Key Reference)

### ISSUE THREAD

**Issue by tgharib** [peterjschroeder/bukut#3]
It would be nice to have the below text pop-up after pressing `h` or `?` within the TUI instead of referring to the github README:

```
Keys
Enter opens url in browser.
Del deletes a bookmark
Insert adds a new bookmark
Ctrl+e edits a bookmark
Ctrl+y copies url to clipboard
Ctrl+q exits the program
Ctrl+a open url through the Wayback Machine
```

**Comment by peterjschroeder** [comment]
I added it Ctrl+h. I go with the control keys because while in the bookmark list the regular keys search. I am leaving this open for now as there is a small bug where it won't refocus to the searchbar when exiting the help screen. Also, color is suppose to work in the help screen but isn't.

**Comment by peterjschroeder** [comment]
Although the screen is added, it can't currently be colored. I believe this is due to design of asciimatics. Color seems to need a certain widget on the screen and focused for it to be color aware. Closing this for now as I can't think of a workaround.
